In [21]:
import pandas as pd

df = pd.DataFrame({
    "color": ["green", "red", "blue", "green"],
    "size": ["M", "L", "XL", "M"],
    "price": [10.1, 13.5, 15.3, 12.8],
    "classlabel": ["class1", "class2", "class1", "class2"]
})

df

   color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1
3  green    M   12.8     class2

In [ ]:
# Ordinal mapping
size_mapping = {
    "M": 1,
    "L": 2,
    "XL": 3
}
df["size"] = df["size"].map(size_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1
3  green     1   12.8     class2

In [26]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()

y = class_le.fit_transform(df["classlabel"])

y

class_le.classes_

class_le.inverse_transform(y)

array(['class1', 'class2', 'class1', 'class2'], dtype=object)

In [ ]:
# One-hot encoding

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe.fit_transform(df[["color"]]).toarray()

ohe.categories # 'auto'

'auto'

In [28]:
# One-hot encoding

import pandas as pd

pd.get_dummies(df["color"])

pd.get_dummies(df, columns=["color"])

  size  price classlabel  color_blue  color_green  color_red
0    M   10.1     class1       False         True      False
1    L   13.5     class2       False        False       True
2   XL   15.3     class1        True        False      False
3    M   12.8     class2       False         True      False